# -*- coding: utf-8 -*-
"""bot_gamification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3vAOBW5aKg5aM4LFH21QcMSDavYlrAa
"""

!pip install aiogram==2.25.2 gspread oauth2client nest_asyncio

!pip install aiocron

# === Импорты ===
from aiogram import Bot, Dispatcher, types
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram.utils import executor
import logging
import nest_asyncio
import random
import asyncio
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import aiocron
from datetime import datetime, timedelta
import pytz

# === Настройки ===
API_TOKEN = '7927451877:AAE3zEyNcNTXTjTqwUCa3nc_xomAPKVewDc'

bot = Bot(token=API_TOKEN, parse_mode=types.ParseMode.HTML)
storage = MemoryStorage()
dp = Dispatcher(bot, storage=storage)

nest_asyncio.apply()

# === Простая версия хранения прогресса через словарь ===
user_data = {}
daily_points = {}

# === Настройка Google Sheets ===
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name("/content/credentials.json", scope)
client = gspread.authorize(creds)
sheet = client.open("GamificationData").worksheet("Баллы")

# === Функция обновления прогресса в таблице ===
def update_progress(user_id, username=None, day=None, points=0, badge=None):
    users = sheet.col_values(1)
    if str(user_id) in users:
        row = users.index(str(user_id)) + 1
    else:
        row = len(users) + 1
        sheet.update_cell(row, 1, str(user_id))
        sheet.update_cell(row, 2, "")
        sheet.update_cell(row, 3, username or "Нет username")
        sheet.update_cell(row, 4, "0")
        sheet.update_cell(row, 5, "")

    if day:
        days = sheet.cell(row, 2).value or ""
        if str(day) not in days:
            new_days = days + f" {day}" if days else str(day)
            sheet.update_cell(row, 2, new_days)

    if points:
        current_points = int(sheet.cell(row, 4).value or 0)
        sheet.update_cell(row, 4, current_points + points)
        daily_points[str(user_id)] = daily_points.get(str(user_id), 0) + points

    if badge:
        badges = sheet.cell(row, 5).value or ""
        if badge not in badges:
            new_badges = badges + f", {badge}" if badges else badge
            sheet.update_cell(row, 5, new_badges)

# === Автоматическая регистрация нового пользователя ===
@dp.message_handler(commands=['start'])
async def start_message(message: types.Message):
    user_id = message.from_user.id
    username = message.from_user.username or "Нет username"
    update_progress(user_id, username=username)

    keyboard = types.InlineKeyboardMarkup(row_width=2)
    keyboard.add(
        types.InlineKeyboardButton(text="📋 Задания челленджа", url="https://t.me/c/2529786741/15"),
        types.InlineKeyboardButton(text="💬 Чат обратной связи", url="https://t.me/c/2529786741/22")
    )
    keyboard.add(
        types.InlineKeyboardButton(text="👥 Знакомство", url="https://t.me/c/2529786741/26"),
        types.InlineKeyboardButton(text="🎥 Записи эфиров", url="https://t.me/c/2529786741/20")
    )
    keyboard.add(
        types.InlineKeyboardButton(text="🎀 Бонусы", url="https://t.me/c/2529786741/24"),
        types.InlineKeyboardButton(text="👤 Профиль", url="https://t.me/c/2529786741/41")
    )
    keyboard.add(
        types.InlineKeyboardButton(text="🎁 Витрина призов", url="https://t.me/c/2529786741/48")
    )

    await message.answer("✨ Добро пожаловать в челлендж \"Вы ЭТО можете\"!\n\nВыбирайте тему в меню снизу 👇", reply_markup=keyboard)

# === Команда /spin для Колеса фортуны ===
@dp.message_handler(commands=['spin'])
async def spin_wheel(message: types.Message):
    user_id = message.from_user.id
    users = sheet.col_values(1)
    if str(user_id) in users:
        row = users.index(str(user_id)) + 1
        current_points = int(sheet.cell(row, 4).value or 0)
        if current_points < 50:
            await message.answer("⚡ Для запуска Колеса Фортуны нужно набрать минимум 50 баллов! Продолжайте проявляться!")
            return

    prizes = ["+10 баллов", "+20 баллов", "Бейдж 🌟 Проявленность", "Бейдж 🚀 Прорыв"]
    prize = random.choice(prizes)

    if "+10" in prize:
        update_progress(user_id, points=10)
    elif "+20" in prize:
        update_progress(user_id, points=20)
    else:
        badge_name = prize.replace("Бейдж ", "")
        update_progress(user_id, badge=badge_name)

    await message.answer(f"🎉 Поздравляем! Ты выиграла {prize}! 🎁")

# === Правильное начисление баллов по темам ===
@dp.message_handler(lambda message: message.chat.type in ["group", "supergroup"])
async def handle_group_message(message: types.Message):
    user_id = message.from_user.id
    thread_id = str(message.message_thread_id)

    if thread_id == "26":
        update_progress(user_id, points=10)
    elif thread_id == "15":
        update_progress(user_id, points=15)

# === Обработчики дополнительных команд ===
@dp.message_handler(commands=['profile'])
async def profile_command(message: types.Message):
    await message.answer("👤 Ваш Профиль: отслеживайте свои баллы, бейджи и успехи! Переходите: https://t.me/c/2529786741/41")

@dp.message_handler(commands=['vitrina'])
async def vitrina_command(message: types.Message):
    await message.answer("🎁 Витрина призов: обменивайте баллы на подарки! Переходите: https://t.me/c/2529786741/48")

# === Реакции на лайки ===
@dp.callback_query_handler()
async def handle_reaction(callback_query: types.CallbackQuery):
    if callback_query.data in ["👍", "❤️", "🔥"]:
        message = callback_query.message
        if message.reply_to_message:
            reacted_user_id = message.reply_to_message.from_user.id
            update_progress(reacted_user_id, points=5)
            await bot.answer_callback_query(callback_query.id, text="🎉 +5 баллов за поддержку участника!", show_alert=False)

# === Ежедневная рассылка итогов в 22:00 МСК ===
@aiocron.crontab('0 22 * * *')
async def send_daily_summary():
    moscow_tz = pytz.timezone('Europe/Moscow')
    now = datetime.now(moscow_tz)
    for user_id, points in daily_points.items():
        if points > 0:
            try:
                await bot.send_message(user_id, f"✨ Итоги дня ({now.strftime('%d.%m.%Y')}):\nСегодня ты заработала {points} баллов! Продолжай в том же духе! 🔥")
            except Exception as e:
                logging.error(f"Не удалось отправить сообщение {user_id}: {e}")
    daily_points.clear()

# === Запуск бота ===
if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    executor.start_polling(dp, skip_updates=True)